//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Stepanets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string CarModel { get; set; }
        public int BrokenPartID { get; set; }
        public Nullable<int> UsedPartID { get; set; }
        public int ServiceID { get; set; }
        public string Status { get; set; }
        public decimal RepairCost { get; set; }
        public decimal FinalProfit { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
