//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Stepanets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spares
    {
        public int ID { get; set; }
        public string SpareName { get; set; }
        public decimal PurchasePrice { get; set; }
        public int Quantity { get; set; }
        public int MinimumStockLevel { get; set; }
        public decimal RepairMarkup { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
